name: Docker Image CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - run: docker build -t webserver .
      - run: docker run -p 80:80 webserver
