name: Docker Image CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - run: podman build -t screen ./project-screen
      - run: podman run -p 8080:8080 screen
