name: Docker build/run CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Stop Docker container
        run: docker stop screen || true

      - name: Remove Docker container
        run: docker rm screen || true
        
      - name: Build
        run: docker build -t screen -f screen/Dockerfile .

      - name: Run
        # env:
        #   REACT_APP_USERNAME: ${{ secrets.TRUSTWORKS_USERNAME }}
        #   REACT_APP_PASSWORD: ${{ secrets.TRUSTWORKS_PASSWORD }}
          
        run: docker run -d --name screen -p 3000:3000 screen
          # -e REACT_APP_USERNAME=${{ secrets.TRUSTWORKS_USERNAME }} \
          # -e REACT_APP_PASSWORD=${{ secrets.TRUSTWORKS_PASSWORD }} \
