name: Docker build/run CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Stop Docker container
        run: docker stop screen

      - name: Remove Docker container
        run: docker rm screen
        
      - name: Build
        run: docker build -t screen -f screen/Dockerfile .
      
      - name: Run
        run: docker run -d --restart=always --name screen -p 3000:3000 screen
